pipeline {
  agent any
  stages {	
	stage('Maven Compile'){
		steps{
			echo 'Project compile stage'		
			bat label: 'Changing directory', script: '''cd hello-world-jenkins'''
			bat label: 'Compilation running', script: '''mvn compile'''
	       	}
	}
	
	stage('Unit Test') {
	   steps {
			echo 'Project Testing stage'			
			bat label: 'Test running', script: '''mvn test'''
	     }
   	}

	stage('Jacoco Coverage Report') {
        	steps{
        			//cd hello-world-jenkins
        			
            		jacoco()            		
		}
	}
       
       stage('SonarQube'){
		steps{
		 		//cd hello-world-jenkins
				bat label: '', script: '''mvn sonar:sonar \
				-Dsonar.host.url=http://localhost:9000 \
				-Dsonar.login=4e786f6325bc6bac3fca0554d8f0dbf7a3a5b719'''
			}
   		}
	
	stage('Maven Package'){
		steps{
			echo 'Hello World!'
			echo 'Project packaging stage'
			//cd hello-world-jenkins
			bat label: 'Project packaging', script: '''mvn package'''
		}
	} 		
    
  }
}
